version: '3.8'

services:
  mcp-agent-tracker:
    build: .
    container_name: mcp-agent-tracker-dev
    environment:
      - ENVIRONMENT=development
      - USER_ID=dev_user
      - DB_PATH=/app/data/agent_tracker.db
      # Use SQLite for development
      # - DATABASE_URL=postgresql://mcp_user:mcp_password@postgres:5432/mcp_tracker
      # Conversation tracking configuration
      - ENABLE_BACKGROUND_MONITORING=true
      - MONITORING_INTERVAL_SECONDS=60
      - ENABLE_AUTOMATIC_METADATA=true
      # Logging configuration
      - LOG_LEVEL=DEBUG
      - LOG_FILE=/app/logs/agent_tracker.log
      # Performance configuration
      - MAX_EXECUTION_TIME_MS=30000
      - BATCH_LOG_SIZE=100
    volumes:
      # Mount source code for development
      - .:/app
      # Persistent data storage
      - mcp_dev_data:/app/data
      # Optional: Mount logs directory
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'bash',
          '-c',
          'source .venv/bin/activate && python -c "from models import get_session_factory; get_session_factory()()"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mcp_dev_data:
    driver: local

networks:
  default:
    name: mcp-dev-network
